### PR TITLE
1. Change the endianness of color storage variables, easy convert to …

### PR DESCRIPTION
**Pull request by SanCheung**
1. Change the endianness of color storage variables, easy convert to GDI+/Direct2D color.
2. Adjust Gradient parse process, now support <defs> post definition.

### CODE REVIEW

**Comment by technosaurus** [comment]
Why not just leave it and do something like:
```c
#ifndef NSVG_RGB //define your own version if you want bgra, etc...
#define NSVG_RGB(r, g, b) (((unsigned int)r) | ((unsigned int)g << 8) | ((unsigned int)b << 16))
#endif 
```
Then you can just define your own before including it if you are on a different platform.
It could probably do with NSVG_RGBA(r,g,b,a) too.

**Comment by SanCheung** [comment]
> en you can just define your own before including it if you are on a different platform.
> It could probably do with NSVG_RGBA(r,g,b,a) too.

**Comment by SanCheung** [comment]
> NSVG_RGB

The master version is like this, I think I should follow the original style.

**Comment by technosaurus** [comment]
The style of the project is also not to break existing working code when there's a simple alternative that won't break it.

**Pull request closed without merging**
