### PR TITLE
add basic support for clip paths

### PR DESCRIPTION
**Pull request by poke1024**
Currently, the NanoSVG parser and rasterizer don't handle clip-paths at all (and won't even ignore them). This PR adds some support for them (via stencil bit buffers, including support for multiple intersecting clip paths).

Here's a demo file exported from Affinity Designer using folded clip paths:

[clip-path-ball.zip](https://github.com/memononen/nanosvg/files/2195677/clip-path-ball.zip)

With the current master NanoSVG, this is generated:

without-patches

With the PR, the image is rendered correctly:

with-patches

### CODE REVIEW

**Comment by SergeySlice** [comment]
Good improvement.

**Comment by SergeySlice** [comment]
Somehow I made a mistake. Can you propose what is wrong?

**Comment by poke1024** [comment]
This is the default PR? Then it's a bug. May I ask which system/compiler you're on?

It looks like the mask is correctly computed, but then not correctly applied to the left top rectangle, even though it's applied to all other elements correctly - which is strange.

In `nanosvgrast.h`, the code that finds which clip mask applies is in line 1219:

`unsigned char* stencil = &r->stencil[r->stencilSize * clip->index[i] + y * r->stencilStride];`

You could try changing that line to:

`unsigned char* stencil = &r->stencil[r->stencilSize * 0 + y * r->stencilStride];`

which means, it will always use clip mask #0 for clipping (which is the central circle in this svg). If this makes a difference, then there's a problem with `clip->index[i]` I need to investigate.

**Comment by poke1024** [comment]
As an aside: here's a better test case for the overall functionality of intersecting masks:

[clip-path-ball.zip](https://github.com/memononen/nanosvg/files/2216844/clip-path-ball.zip)

Correct rendering:

bildschirmfoto 2018-07-22 um 11 07 03

All elements without any clipping:

bildschirmfoto 2018-07-22 um 11 05 58

**Comment by SergeySlice** [comment]
Hello,
I am using macOS 10.13.6 with Xcode9.4.1. clang-902.0.39.2
But the problem is not there. There are problems:
1. I compiled it for UEFI so I can't use standard libraries (sscan, malloc, realloc, sqrtf... etc). All of them are replaced with other functions even with other arguments.
2. I already implemented almost all of pull requests as I want as much features as possible. But they are weak compatible with each other. For example your PR based on pure project while I already have style and groups implemented, different x,y scaling, image and text initial support. So applying your diff I have to carefully check if it is conflict with other patches. I think it will be good if Mikko will accept all PR which is tested as correct or non-wrong so that next developers based on full project.

Anyway new results:
if I change index[i] to index[0] then there are no differencies in output.
You second test picture rendered as

**Comment by SergeySlice** [comment]
I also want this syntax to be supported :(
~~~
	<defs>
		<rect id="SVGID_1_" y="0" width="841.89" height="595.28"/>
	</defs>
	<clipPath id="SVGID_2_">
		<use xlink:href="#SVGID_1_"  overflow="visible"/>
	</clipPath>
~~~

**Comment by SergeySlice** [comment]
I see with your both clip-path-ball.svg the problem is with <rect>.

**Comment by SergeySlice** [comment]
@poke1024 
I have to thank you for this big feature. After some testing and corrections I have fully working solution.
This image rendered fine
[Clover2.svg.zip](https://github.com/memononen/nanosvg/files/2271596/Clover2.svg.zip)

My sources are quite different now from Mikko project because I implement several features and I had to change logic of shape scaling. 
For example this shape
~~~
  <rect x="45.802" y="53.435" width="189.886" height="85.878" style="fill: rgb(216, 216, 216);" transform="matrix(0.93358, 0.358368, -0.358368, 0.933581, 43.885579, -44.037379)"/>
~~~
"x,y,width,heigth" defines coordinates in Design Space (DS).
"transform" defines coordinates in Composition Space (CS).
Should we immediately transform the path to CS? Mikko said Yes, I said No.
Later we have to transform to ViewBox Space (VS),
and finally we have to transform to Drawing Space, our Window Space (WS).
Same operation four times on each point in every path?
I just keep shape->xform and multiply it on new transform at every step.
Then I apply final xform at flattenShape stage.
Just to keep in mind that gradients also should follow shapes.
This way I can make text support with SVG fonts. Each glyph has own DS.
It must be scaled to user's font-size (Font Size).
It must be positioned in text (CS).
The text can be transformed in with group matrix.
Then whole picture will be scaled to VS and WS.

Best wishes!

**Comment by SergeySlice** [comment]
I am not sure if there is a case when we should check clipPath->shapes in nsvg__imageBounds() ?

**Comment by poke1024** [comment]
I'm closing this, as (1) it has not been merged and seems to be too complex a change for general nanosvg, (2) it is now integrated into https://github.com/poke1024/tove2d with a broader focus, and having it in nanosvg would actually cause me a lot of merging headaches.

**Pull request closed without merging**
