### PR TITLE
Remove unnecessary parentheses

### PR DESCRIPTION
**Pull request by shlyakpavel**
This pull request doesn't fix anything. Extra parentheses are not necessary so I removed them to improve code readability.

### CODE REVIEW

**Comment by shlyakpavel** [comment]
Can you please merge it on 30 Dec, 2021?
I will tell my friends that my pull requests take 3 years to review :D

**Comment by oehhar** [comment]
Dear Pavel,
I suppose, this will not happen. Only security fixes with well descriped issue and a pull request in a good state will be merged.
In your case, the description is missing.
You may always provide a description why this is critical and give examples which are solved by the patch.

I hope you understand.
Take care,
Harald

**Comment by shlyakpavel** [comment]
Well, I have added the description :)

**Comment by shlyakpavel** [comment]
Can you please merge it on 30 Dec, 2022?
I will tell my friends that my pull requests take 4 years to review :D

**Comment by tesch1** [comment]
If they're true friends, they already know!

**Comment by shlyakpavel** [comment]
Well, there's still an option to merge it on 30 Dec, 2023
5 years anniversary 🥂 🎉 🥳

**Comment by memononen** [comment]
Thanks for the fix! 🎉

**Pull request merged**
